# Логин пользователя

Реализовываю страницу Войти в магазин. Для этого в **routes auth.js** есть метод

```js
router.post('/login', async (req, res) => {
  const user = await User.findById('5eabd3c0cb1946251098ad0e');
  req.session.user = user;
  req.session.isAuthenticated = true;
  req.session.save((err) => {
    if (err) {
      throw err;
    } else {
      res.redirect('/');
    }
  });
});
```

И здесь пока что мы получаем только одного пользователя, который у нас есть в БД, но которого мы удалили уже, тут фиксированный **id**.

Для начало мы обратимся к **try catch**. И в блоке **try** прописываю определенный функционал. Здесь мы так же получим некоторые данные из объекта **req.body т.е. const {} = req.body;** И в странице логина есть два типа данных **const { email, password } = req.body;**

Когда мы делаем **login** то в первую очередь нужно проверить существует ли у нас такой пользователь. И если не существует то тогда мы не сможем войти в систему.

Создаю переменную **const candidate = await User.findOne({ email });** и с помощью модели пользователя я попробую найти пользователя с таким **email**.

Далее если **if** у нас есть переменная **(candidate)** т.е. такой пользователь у нас существует, то тогда мы можем с этим работать.
А иначе **else** если такого пользователя нет то тогда мы будем делать **res.redirect('/auth/login#login')**. Пока просто без сообщений, но мы знаем что такого пользователя не существует. В последствии мы обработаем данный блок.

Если же кандидат существует то после этого необходимо проверить пароли на совпадение. И пока временно пишу такую проверку **const areSame = password === candidate.password**.

```js
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const candidate = await User.findOne({ email });
    if (candidate) {
      const areSame = password === candidate.password;
    } else {
      res.redirect('/auth/login#login');
    }
  } catch (e) {
    console.log(e);
  }
  const user = await User.findById('5eabd3c0cb1946251098ad0e');
  req.session.user = user;
  req.session.isAuthenticated = true;
  req.session.save((err) => {
    if (err) {
      throw err;
    } else {
      res.redirect('/');
    }
  });
});
```

В цикле **if** пишем еще один **if** если **areSame** находится в значении **true**, то тогда мы можем успешно делать **redirect** на страницу системы, а иначе мы будем также выдавать сообщение об ошибке и редиректить обратно на страницу логина.

И посути мы берем все что мы написали до этого и складываем в успешный логин пользователя. только вот это удаляю **const user = await User.findById('5eabd3c0cb1946251098ad0e');**

И просто присваиваю переменную **candidate**. Вот так **req.session.user = candidate;**

```js
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const candidate = await User.findOne({ email });

    if (candidate) {
      const areSame = password === candidate.password;
      if (areSame) {
        req.session.user = candidate;
        req.session.isAuthenticated = true;
        req.session.save((err) => {
          if (err) {
            throw err;
          } else {
            res.redirect('/');
          }
        });
      } else {
        res.redirect('/auth/login#login');
      }
    } else {
      res.redirect('/auth/login#login');
    }
  } catch (e) {
    console.log(e);
  }
});
```
И полный файл

```js
// routes outh.js
const { Router } = require('express');
const User = require('../models/user');
const router = Router();

router.get('/login', async (req, res) => {
  res.render('auth/login', {
    title: 'Авторизация',
    isLogin: true,
  });
});

router.get('/logout', async (req, res) => {
  req.session.destroy(() => {
    res.redirect('/auth/login#login');
  });
});

router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const candidate = await User.findOne({ email });

    if (candidate) {
      const areSame = password === candidate.password;
      if (areSame) {
        req.session.user = candidate;
        req.session.isAuthenticated = true;
        req.session.save((err) => {
          if (err) {
            throw err;
          } else {
            res.redirect('/');
          }
        });
      } else {
        res.redirect('/auth/login#login');
      }
    } else {
      res.redirect('/auth/login#login');
    }
  } catch (e) {
    console.log(e);
  }
});

router.post('/register', async (req, res) => {
  try {
    const { email, password, repead, name } = req.body;
    const candidate = await User.findOne({ email });
    if (candidate) {
      res.redirect('/auth/login#register');
    } else {
      const user = new User({
        email,
        name,
        password,
        cart: { items: [] },
      });
      await user.save();
      res.redirect('/auth/login#login');
    }
  } catch (e) {
    console.log(e);
  }
});

module.exports = router;
``` 

Все работает. При неправильном вводе перебрасывает назад на страницу. При введенных коректных данных входит в систему.
